### ISSUE TITLE
xmr-stak-cpu

### ISSUE THREAD

**Issue by z1y** [boredazfcuk/mining#3]
Hi boredfriend,

Can you assist me with xmr-stak-cpu please?

I want to create script to auto-run it and to keep the window hidden. 
Also if possible, to relaunch it if its closed and maybe make an output text file.

I know i ask too much. Sorry for bothering you.

Best Regards

**Comment by boredazfcuk** [comment]
https://github.com/boredazfcuk/mining/blob/master/Wrapper-ccminer.vbs

I've not had time to look at logging to a file, but it should run your miner and restart it if it quits out.

Just change the name of the .exe on line 11 to match yours and change the parameters on line 12 too.

You'll need to launch it with wscript.exe for it to be invisible. Make sure you place it in the same folder as the xmr-stak-cpu.exe file.

Edit: From what I've read about that miner, you need to set the httpd_port option and it will let you connect to the miner with your web browser for stats. Prob best to do that if you want to see the output.

**Comment by z1y** [comment]
But line 12 is about pool adress, username, pass etc..
I already have a config along the xmr-stak-cpu.

Can we change instead of parameters to load config only? :)

**Comment by boredazfcuk** [comment]
Line 12 is to define additional parameters you want to pass to the miner.
Change line 12 to Parameters="Config.txt" if you just want to tell it to load a config file.
If you don't want to pass any parameters, just change it to Parameters=""
I think that should work, but I've not been able to test it as I'm at work.

**Comment by z1y** [comment]
Hi again.
I get error:
Line : 27
Char: 2
Error: Unable to wait for process.
Code: 80020009
Source: WshShell.run

**Comment by z1y** [comment]
I've managed to get what i wanted using Windows Task Scheduler. (Auto start & hidden)

Now I need to research about remote hash rate monitoring. 

Thanks for your help.

**Comment by boredazfcuk** [comment]
Yes, you need to launch all my scripts from task scheduler (with the 'highest privileges' check box ticked) or the scripts won't have the permissions required to run.
